config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  
  get 'calculator', to: 'main#calculator'

  resources :todos, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    
    # override in the case the json is empty
    def todo_items
        if self[:todo_items]
            self[:todo_items]
        else 
            '[]'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController

   def index
       
   end

   def calculator

   end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    # todo change to show all lists
    def index
        # move to show and grab by ID
        @todos = Todo.all
    end

    def edit
        @todo = Todo.find(params[:id])

        if (@todo)
            # todo check if this needs a default value
            render :edit
        else
            redirect_to todos_path
        end
    end

    def new
        @todo = Todo.new
    end

    # todo double check this
    def create
        @todo = Todo.new(todo_attributes)

        if @todo.save
            redirect_to(edit_todo_path(id: @todo.id))
        else
            # todo add error messages
            render('new')
        end
    end

    # Ajax Only For Now
    def update 
        # todo handle case where todo doesn't exist
        todo = Todo.find(params[:id])
        todo.todo_items = params[:data];
        todo.save

        render json: params[:data]
    end

    def destroy
        todo = Todo.find(params[:id])
        todo.destroy

        redirect_to(todos_path)
    end

    private

    def todo_attributes
        params.require(:todo).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueScribbles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# 
      Turbolinks causing problems, just disabling for now, 
      Due to inlining JS, todo: figure this out later. Might need to change how the JS is included.
      Either a separate layout, or a conditional that includes it here maybe...?
    %>
    <meta name="turbolinks-visit-control" content="reload">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :js %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/calculator.html.erb
<% content_for :js do %>
    <%= javascript_pack_tag "calculator" %>
<% end %>

<div class="container my-3">
    <h1>Calculator</h1> 

    <div id="root">
        <simple-calculator/>    
    </div>
</div>

app/views/main/index.html.erb
<div id="root">
    <div class="container">
    <h1>Main Page</h1>
    
    <div class="row">
        <div class="col-12">
            <a href="<%= todos_path %>">View Todo Lists</a>
        </div>
    </div>
    </div>


</div>

app/views/todos/edit.html.erb
<% content_for :js do %>
    <%= javascript_pack_tag "todo" %>
<% end %>

<span data-todo-list="<%= @todo.todo_items %>"></span>

<div class="container my-3">
    <div class="row">
        <a class="col-6" href="<%= todos_path %>">Go Back</a>
        <%= form_tag( todo_path(id: @todo.id) , method: "DELETE", class: 'col-6 float-right text-right') do |f| %>
            <%= submit_tag('Delete This Item', class: 'btn btn-danger') %>
        <% end %>
    </div>

    <div id="root">
        <todo-items>
            <div slot="header" slot-scope="{count}" class="row">
                <div class="col-12">
                    <h1>Todo List #<%= @todo.id %></h1>
                    <h5 class="mb-5"><%= @todo.name %> ({{count}} items)</h5>
                </div>
            </div>
        </todo-items>
    </div>
</div>

app/views/todos/index.html.erb
<div class="container">
    <div class="float-right mt-2">
        <%= link_to  "Add New List", new_todo_path %>
    </div> 

    <h1>Todo Lists</h1>

    <div class="row">
        <% @todos.each do |item| %>
            <div class="col-sm-6">
                <a href="<%= edit_todo_path(id: item.id) %>">
                    Todo List #<%= item.id %>: <%= item.name %>
                </a>
            </div>
        <% end %>
    </div>
</div>

app/views/todos/new.html.erb
<div class="container">
    <div class="float-right mt-2">
        <%= link_to  "Go Back", todos_path %>
    </div> 

    <h1 class="mb-5">Create New List</h1>

    <%# add class for the form from BS4 %>
    <%= form_for(@todo) do |f| %>
        <div class="row form-group mb-5">
            <div class="col-sm-4">
                <%# todo check label class %>
                <%= f.label (:name) %>
            </div>

            <div class="col-sm-8">
                <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-12 text-right">
                <%= f.submit("Create New List", class:"btn btn-primary") %>
            </div>
        </div>
    <% end %>
</div>